name: shopping
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/profile.jpg
    
  uses-material-design: true
